feat(azure): Add proper mount options for AzureFile or Shared Disk

diff --git a/drupal/templates/cronjob/drupal.yaml b/drupal/templates/cronjob/drupal.yaml
--- a/drupal/templates/cronjob/drupal.yaml
+++ b/drupal/templates/cronjob/drupal.yaml
@@ -26,6 +26,25 @@ spec:
         spec:
           restartPolicy: OnFailure
           containers:
+          - name: drush
+            image: "{{ .Values.drupal.image }}:{{ default .Chart.AppVersion .Values.drupal.tag }}"
+            imagePullPolicy: {{ default "" .Values.drupal.imagePullPolicy | quote }}
+            command:
+            - '/bin/sh'
+            - '-c'
+            - |
+                # Errors should fail the job
+                set -e
+
+                # Wait for DB to be available
+                until drush sql:query 'SHOW TABLES;'; do echo Waiting for DB; sleep 3; done
+                echo DB available
+
+                # Check Drush status
+                drush status
+
+                # Run cron
+                drush -y core-cron
 {{- if .Values.postgresql.pgbouncer.enabled }}
           - name: pgbouncer
             image: mcr.microsoft.com/azure-oss-db-tools/pgbouncer-sidecar:latest
@@ -49,25 +68,6 @@ spec:
               capabilities:
                 drop: ['all']
 {{- end  }}
-          - name: drush
-            image: "{{ .Values.drupal.image }}:{{ default .Chart.AppVersion .Values.drupal.tag }}"
-            imagePullPolicy: {{ default "" .Values.drupal.imagePullPolicy | quote }}
-            command:
-            - '/bin/sh'
-            - '-c'
-            - |
-                # Errors should fail the job
-                set -e
-
-                # Wait for DB to be available
-                until drush sql:query 'SHOW TABLES;'; do echo Waiting for DB; sleep 3; done
-                echo DB available
-
-                # Check Drush status
-                drush status
-
-                # Run cron
-                drush -y core-cron
             env:
 {{- if .Values.external.enabled }}
             - name: EXTERNAL_PASSWORD
@@ -196,6 +196,18 @@ spec:
             emptyDir: {}
           - name: config-sync
             emptyDir: {}
+{{- if .Values.drupal.persistence.enabled }}
+          - name: files
+            persistentVolumeClaim:
+              claimName: {{ template "drupal.fullname" . }}-drupal
+{{- else if or (.Values.azureFile.enabled) (.Values.sharedDisk.enabled) }}
+      - name: files-public
+        persistentVolumeClaim:
+          claimName: {{ include "drupal.fullname" . }}-public
+      - name: files-private
+        persistentVolumeClaim:
+          claimName: {{ include "drupal.fullname" . }}-private
+{{- else if not .Values.drupal.disableDefaultFilesMount }}
           - name: files
             emptyDir: {}
 {{- end }}
@@ -203,4 +215,8 @@ spec:
           - name: configfiles
             secret:
               secretName: {{ include "drupal.fullname" . }}-pgbouncer
+{{- end }}
+{{- if .Values.drupal.volumes }}
+{{ toYaml .Values.drupal.volumes | indent 10 }}
+{{- end }}
 {{- end }}
